Name: product.rpc
ListenOn: 127.0.0.1:8081
Etcd:
  Hosts:
  - 0.0.0.0:2379
  Key: product.rpc
Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/user?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1:6379
    Type: node
    Pass:
BizRedis:
  Host: 127.0.0.1:6379
  Pass:
  Type: node